### ISSUE TITLE
bug codesnippet 

### ISSUE THREAD

**Issue by acciobugs** [Gochip/labsis_seg#27]
Al **editar** un artículo y seleccionar codesnippet, no permite seleccionar el combo, se cierra solo...
problema del front. 
Al crear un art. nuevo, funciona bien.
Hay que ver para que se respete el formato en la página una vez que se guarde el artículo.

**Comment by Gochip** [comment]
@ibarrionuevo en qué lugar seleccionás CodeSnippet?

**Comment by Gochip** [comment]
Ah, esto está en la rama testing. Ahí lo encontré.
